-- Dravonix WhatsApp AI Platform
-- Phase 6C: staging billing automation foundation. Migrations 28 and 29 are
-- immutable and are never touched here -- this migration only builds
-- forward. All new RPCs below are service_role-only (called exclusively by
-- the new apps/workers/billing-scheduler cron Worker), except the one
-- Super Admin read RPC at the end, which follows the exact
-- current_platform_role() = 'super_admin' gating pattern already
-- established by admin_assign_plan (migration 17).
--
-- Scope (deliberately staying inside what Phase 6C asked for -- no
-- Super Admin billing UI, no WhatsApp billing notifications, no discounts/
-- proration/refunds/taxes):
--
--   1. invoices.billing_period_start / billing_period_end -- the
--      authoritative billing-cycle identity for a subscription invoice
--      (Phase 4). A partial unique index on
--      (company_id, billing_period_start, billing_period_end) is the
--      idempotency guarantee: a scheduler that runs twice, retries, or
--      overlaps can never create two invoices for the same cycle -- the
--      second attempt hits unique_violation and is caught as a no-op,
--      exactly mirroring how migration 28/29 already treat
--      payments.provider_reference and payment_attempts'
--      unique(provider, provider_event_id).
--
--   2. billing_invoice_number_seq -- a real Postgres sequence backing a
--      production-safe invoice-number format (DRV-<year>-<6 digits>).
--      Sequences are safe under arbitrary concurrency by construction; no
--      test fixture invoice number (INV-STAGING-TEST-0001 etc.) is ever
--      produced by this path.
--
--   3. billing_reminders -- one idempotency row per (invoice, lifecycle
--      stage, channel). The reminder scheduler checks this table before
--      ever creating a notification, so a rerun/retry/overlap can never
--      send (or record) the same reminder twice.
--
--   4. Five new RPCs, in the order the daily scheduler calls them:
--      generate_due_subscription_invoices, advance_overdue_subscriptions,
--      suspend_expired_grace_subscriptions, send_due_billing_reminders,
--      and the Super-Admin-only read RPC admin_billing_lifecycle_overview.
--      Every state transition uses an existing canonical
--      subscription_state/SubscriptionEvent value from
--      packages/billing/src/stateMachine.ts -- none is invented. Every
--      write is company-scoped by construction (looked up from the
--      subscription/invoice row itself, never a parameter), matching the
--      tenant-isolation discipline already established in migrations 28/29.
--
--   5. Grace-period duration: plan_versions.grace_period_days already
--      exists (migration 7, default 5) with a matching pure calculator,
--      packages/billing/src/gracePeriod.ts's computeGracePeriodEnd -- both
--      unit-tested but never wired into any production code path before
--      this migration (confirmed by repo-wide audit). This migration is
--      the first thing to actually consume that column; no new duration is
--      invented, and the SQL mirrors the exact
--      `startedAt + gracePeriodDays days` arithmetic the TS helper already
--      defines.
--
--   6. Decision point (payment_due -> grace_period timing): the state
--      machine models `payment_due` and `grace_period` as two distinct
--      states connected by `grace_period_started`, but no existing ADR or
--      doc (checked docs/architecture/adr-0006 and
--      BILLING_AND_SUSPENSION.md) defines how long a subscription should
--      sit in bare `payment_due` before `grace_period_started` fires.
--      Resolved here: advance_overdue_subscriptions transitions
--      active/trial -> payment_due and immediately -> grace_period in the
--      same scheduler pass (two real subscription_events rows, using both
--      canonical events faithfully -- payment_due is momentary/transient,
--      not a separately-timed waiting state), because the only duration
--      this codebase actually defines anywhere is the grace period itself
--      (plan_versions.grace_period_days). Inventing a second, undocumented
--      "how long to wait in payment_due" duration would be exactly the
--      kind of invented business rule Phase 6C says not to guess.
--
--   7. Trial first-invoice timing (Phase 26): no existing doc defines this.
--      Resolved here identically to the renewal-invoice rule (7 days
--      before the relevant period end) for consistency -- trial and
--      subscription renewal invoices are generated by the exact same RPC,
--      keyed off current_period_end regardless of whether the subscription
--      is currently `trial` or `active`.
--
--   8. Email sending: Phase 6C's own instruction is to STOP before sending
--      automated external emails if no staging-safety mechanism exists.
--      A repo-wide audit found none (no environment guard, no recipient
--      override, on any customer-facing email send path). This migration
--      and the accompanying Worker therefore only ever produce
--      DB-persisted, dashboard-visible reminder state (billing_reminders +
--      an in-app `notifications` row) -- no email provider is ever
--      invoked from this migration or from apps/workers/billing-scheduler.
--      A render-only, fully unit-tested email template is added in
--      packages/email for later use once a real staging-safety mechanism
--      exists; wiring it to an actual send is explicitly out of scope here.

-- ---------------------------------------------------------------------------
-- 1. Invoice billing-cycle identity.
-- ---------------------------------------------------------------------------

alter table invoices add column billing_period_start date;
alter table invoices add column billing_period_end date;

comment on column invoices.billing_period_start is
  'Company-local calendar date the billed subscription period starts. Null for non-subscription invoices (service_charge/usage_overage) and for any invoice created before migration 30. Set once, at generation time, from subscriptions.current_period_start converted via companies.timezone -- never recomputed.';
comment on column invoices.billing_period_end is
  'Company-local calendar date the billed subscription period ends (this is also the invoice due_date). Together with company_id, the authoritative billing-cycle identity: see invoices_subscription_cycle_key below.';

create unique index invoices_subscription_cycle_key on invoices (company_id, billing_period_start, billing_period_end)
  where kind = 'subscription' and billing_period_start is not null and billing_period_end is not null;

comment on index invoices_subscription_cycle_key is
  'Phase 6C invoice-generation idempotency: at most one subscription invoice may ever exist for a given company + billing cycle, regardless of how many times the scheduler runs, retries, or overlaps. Postgres treats every NULL as distinct under a plain unique index (same reasoning as payments_provider_reference_key in migration 28), so pre-existing rows with null billing_period_start/end are completely unaffected.';

-- ---------------------------------------------------------------------------
-- 2. Production-safe invoice numbering.
-- ---------------------------------------------------------------------------

create sequence billing_invoice_number_seq;

comment on sequence billing_invoice_number_seq is
  'Backs the DRV-<year>-<6 digits> invoice number format (Phase 6C). A real Postgres sequence is used specifically because it is safe under arbitrary concurrency by construction -- no advisory lock or row lock is needed to avoid a collision. Test/demo fixtures (e.g. INV-STAGING-TEST-0001) are unrelated hand-authored strings and never collide with this format.';

-- ---------------------------------------------------------------------------
-- 3. Reminder idempotency.
-- ---------------------------------------------------------------------------

create type billing_reminder_stage as enum (
  'due_in_7', 'due_in_3', 'due_in_1', 'due_today', 'grace_period_started'
);

create table billing_reminders (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references companies (id) on delete cascade,
  invoice_id uuid not null references invoices (id) on delete cascade,
  stage billing_reminder_stage not null,
  channel text not null default 'in_app',
  sent_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (invoice_id, stage, channel)
);

comment on table billing_reminders is
  'Phase 6C reminder idempotency: one row per (invoice, lifecycle stage, channel) ever created. send_due_billing_reminders checks this table before creating any notification, so a scheduler rerun/retry/overlap can never send (or even record) the same reminder twice. channel is a plain text column (not an enum) so a future channel can be added without a migration -- mirrors notifications.category''s existing text-not-enum convention (migration 8).';

create index billing_reminders_company_id_idx on billing_reminders (company_id);

alter table billing_reminders enable row level security;

create policy billing_reminders_select_member on billing_reminders
  for select
  using (has_company_permission(company_id, 'billing.view'));

revoke insert, update, delete on billing_reminders from public, anon, authenticated;
grant select on billing_reminders to authenticated;
grant select, insert on billing_reminders to service_role;

-- ---------------------------------------------------------------------------
-- 4. generate_due_subscription_invoices: one invoice per subscription
--    billing cycle, 7 days before the relevant period end (trial or
--    active alike). service_role only -- called by the daily scheduler,
--    never by an end-user JWT (there is no client-facing "generate an
--    invoice" action; invoices are either system-generated here or,
--    historically, hand-inserted only for the one-off staging test
--    fixture that predates this migration).
-- ---------------------------------------------------------------------------

create or replace function generate_due_subscription_invoices()
returns table (company_id uuid, invoice_id uuid, invoice_number text)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_sub record;
  v_local_period_start date;
  v_local_period_end date;
  v_invoice_id uuid;
  v_invoice_number text;
begin
  for v_sub in
    select s.id as subscription_id, s.company_id, s.state, s.current_period_start, s.current_period_end,
           pv.monthly_price, pv.currency, c.timezone
    from public.subscriptions s
    join public.plan_versions pv on pv.id = s.plan_version_id
    join public.companies c on c.id = s.company_id
    where s.state in ('trial', 'active')
      and s.current_period_end is not null
      and s.current_period_end <= now() + interval '7 days'
    for update of s skip locked
  loop
    v_local_period_start := (v_sub.current_period_start at time zone coalesce(v_sub.timezone, 'UTC'))::date;
    v_local_period_end := (v_sub.current_period_end at time zone coalesce(v_sub.timezone, 'UTC'))::date;

    begin
      v_invoice_number := 'DRV-' || to_char(now(), 'YYYY') || '-' || lpad(nextval('public.billing_invoice_number_seq')::text, 6, '0');

      insert into public.invoices (
        company_id, kind, invoice_number, status, currency,
        subtotal, tax, discount, total, due_date,
        billing_period_start, billing_period_end
      ) values (
        v_sub.company_id, 'subscription', v_invoice_number, 'pending', v_sub.currency,
        v_sub.monthly_price, 0, 0, v_sub.monthly_price, v_local_period_end,
        v_local_period_start, v_local_period_end
      )
      returning id into v_invoice_id;

      insert into public.audit_logs (company_id, actor_user_id, actor_type, action, target_type, target_id, metadata)
        values (v_sub.company_id, null, 'system', 'invoice_generated', 'invoice', v_invoice_id::text,
                jsonb_build_object(
                  'invoice_number', v_invoice_number,
                  'billing_period_start', v_local_period_start,
                  'billing_period_end', v_local_period_end,
                  'total', v_sub.monthly_price,
                  'currency', v_sub.currency,
                  'subscription_state_at_generation', v_sub.state
                ));

      company_id := v_sub.company_id;
      invoice_id := v_invoice_id;
      invoice_number := v_invoice_number;
      return next;
    exception when unique_violation then
      -- An invoice for this exact company+cycle already exists (a prior
      -- run, a retry, or an overlapping concurrent run) -- safe no-op.
      continue;
    end;
  end loop;
end;
$$;

comment on function generate_due_subscription_invoices() is
  'Phase 6C: generates one pending subscription invoice per (trial/active) subscription whose current_period_end falls within 7 days, using the plan_version''s own price/currency (never client-supplied) and the company''s local calendar dates for the billing period. Idempotent via invoices_subscription_cycle_key -- a duplicate attempt for the same cycle is a caught, silent no-op. `for update of s skip locked` lets concurrent/overlapping scheduler invocations each make forward progress on disjoint subscriptions instead of blocking on each other.';

revoke all on function generate_due_subscription_invoices() from public, anon, authenticated;
grant execute on function generate_due_subscription_invoices() to service_role;

-- ---------------------------------------------------------------------------
-- 5. advance_overdue_subscriptions: active/trial -> payment_due ->
--    grace_period for any subscription whose current period has lapsed
--    with its cycle invoice still unpaid. See migration header point 6 for
--    why payment_due and grace_period_started both fire in the same pass.
-- ---------------------------------------------------------------------------

create or replace function advance_overdue_subscriptions()
returns table (company_id uuid, subscription_id uuid, new_state subscription_state)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_sub record;
  v_due_event text;
  v_grace_days integer;
  v_grace_period_end timestamptz;
begin
  for v_sub in
    select s.id as subscription_id, s.company_id, s.state, s.current_period_end, pv.grace_period_days
    from public.subscriptions s
    join public.plan_versions pv on pv.id = s.plan_version_id
    where s.state in ('trial', 'active')
      and s.current_period_end is not null
      and s.current_period_end < now()
      and not exists (
        select 1 from public.invoices i
        where i.company_id = s.company_id
          and i.kind = 'subscription'
          and i.billing_period_end = (s.current_period_end at time zone 'UTC')::date
          and i.status = 'paid'
      )
    for update of s
  loop
    v_due_event := case v_sub.state when 'trial' then 'trial_ended_without_payment' else 'payment_failed' end;
    v_grace_days := v_sub.grace_period_days;
    -- Grace period counts from the actual lapse (current_period_end), never
    -- from "now" (the moment the scheduler happens to process it) -- a
    -- delayed/backfilled scheduler run must never grant a subscription
    -- bonus grace time it wouldn't have had if the scheduler had run daily
    -- without interruption. Mirrors computeGracePeriodEnd's own
    -- (startedAt, gracePeriodDays) contract exactly, with startedAt =
    -- current_period_end.
    v_grace_period_end := v_sub.current_period_end + make_interval(days => v_grace_days);

    update public.subscriptions set state = 'payment_due' where id = v_sub.subscription_id;

    insert into public.subscription_events (company_id, subscription_id, from_state, to_state, event, is_manual_override, actor_user_id, notes)
      values (v_sub.company_id, v_sub.subscription_id, v_sub.state, 'payment_due', v_due_event, false, null,
              'scheduler: current billing period ended without a paid invoice');

    update public.subscriptions
      set state = 'grace_period', grace_period_end = v_grace_period_end
      where id = v_sub.subscription_id;

    insert into public.subscription_events (company_id, subscription_id, from_state, to_state, event, is_manual_override, actor_user_id, notes)
      values (v_sub.company_id, v_sub.subscription_id, 'payment_due', 'grace_period', 'grace_period_started', false, null,
              'scheduler: grace period of ' || v_grace_days || ' day(s) per plan');

    insert into public.audit_logs (company_id, actor_user_id, actor_type, action, target_type, target_id, metadata)
      values (v_sub.company_id, null, 'system', 'payment_due', 'subscription', v_sub.subscription_id::text,
              jsonb_build_object('from_state', v_sub.state));
    insert into public.audit_logs (company_id, actor_user_id, actor_type, action, target_type, target_id, metadata)
      values (v_sub.company_id, null, 'system', 'grace_period_started', 'subscription', v_sub.subscription_id::text,
              jsonb_build_object('grace_period_end', v_grace_period_end, 'grace_period_days', v_grace_days));

    company_id := v_sub.company_id;
    subscription_id := v_sub.subscription_id;
    new_state := 'grace_period';
    return next;
  end loop;
end;
$$;

comment on function advance_overdue_subscriptions() is
  'Phase 6C: transitions any trial/active subscription whose current_period_end has passed with its cycle invoice still unpaid through payment_due (trial_ended_without_payment or payment_failed, matching the real prior state) and immediately into grace_period (grace_period_started), using plan_versions.grace_period_days via the exact arithmetic packages/billing/src/gracePeriod.ts already defines. Idempotent: re-running finds no subscriptions still in trial/active with a lapsed period once this has run once (the WHERE clause naturally excludes anything already in payment_due/grace_period/suspended).';

revoke all on function advance_overdue_subscriptions() from public, anon, authenticated;
grant execute on function advance_overdue_subscriptions() to service_role;

-- ---------------------------------------------------------------------------
-- 6. suspend_expired_grace_subscriptions: grace_period -> suspended once
--    grace_period_end has passed. Never manually_suspended -- that state is
--    reserved for explicit platform/admin action (admin_change_subscription_state,
--    migration 17), never touched by this scheduler.
-- ---------------------------------------------------------------------------

create or replace function suspend_expired_grace_subscriptions()
returns table (company_id uuid, subscription_id uuid)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_sub record;
begin
  for v_sub in
    select s.id as subscription_id, s.company_id
    from public.subscriptions s
    where s.state = 'grace_period'
      and s.grace_period_end is not null
      and s.grace_period_end < now()
    for update of s
  loop
    update public.subscriptions set state = 'suspended' where id = v_sub.subscription_id;

    insert into public.subscription_events (company_id, subscription_id, from_state, to_state, event, is_manual_override, actor_user_id, notes)
      values (v_sub.company_id, v_sub.subscription_id, 'grace_period', 'suspended', 'grace_period_expired', false, null,
              'scheduler: grace period elapsed without payment');

    insert into public.audit_logs (company_id, actor_user_id, actor_type, action, target_type, target_id, metadata)
      values (v_sub.company_id, null, 'system', 'subscription_suspended', 'subscription', v_sub.subscription_id::text, '{}'::jsonb);

    company_id := v_sub.company_id;
    subscription_id := v_sub.subscription_id;
    return next;
  end loop;
end;
$$;

comment on function suspend_expired_grace_subscriptions() is
  'Phase 6C: the previously-unbuilt grace-period-expiry cron job (TASKS.md). Transitions grace_period -> suspended via the canonical grace_period_expired event once grace_period_end has passed. Distinct from manually_suspended, which remains exclusively an explicit admin action (migration 17) that this function never produces or touches. A suspended subscription is already correctly blocked from chargeable operations by the existing packages/billing/src/entitlementGuard.ts (isServiceBlocked includes "suspended") -- no new entitlement/guard logic is added here.';

revoke all on function suspend_expired_grace_subscriptions() from public, anon, authenticated;
grant execute on function suspend_expired_grace_subscriptions() to service_role;

-- ---------------------------------------------------------------------------
-- 7. send_due_billing_reminders: dashboard-visible (in_app notifications
--    row) + auditable reminder state only. No email provider is ever
--    invoked here -- see migration header point 8.
-- ---------------------------------------------------------------------------

create or replace function send_due_billing_reminders()
returns table (company_id uuid, invoice_id uuid, stage billing_reminder_stage)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_row record;
  v_stage public.billing_reminder_stage;
  v_days_remaining integer;
  v_local_today date;
  v_subject text;
  v_body text;
begin
  for v_row in
    select i.id as invoice_id, i.company_id, i.invoice_number, i.total, i.currency, i.due_date,
           s.state as subscription_state, c.timezone, c.name as company_name
    from public.invoices i
    join public.companies c on c.id = i.company_id
    left join public.subscriptions s on s.company_id = i.company_id
    where i.kind = 'subscription' and i.status = 'pending'
  loop
    v_local_today := (now() at time zone coalesce(v_row.timezone, 'UTC'))::date;
    v_days_remaining := v_row.due_date - v_local_today;

    if v_row.subscription_state = 'grace_period' then
      v_stage := 'grace_period_started';
    elsif v_days_remaining <= 0 then
      v_stage := 'due_today';
    elsif v_days_remaining = 1 then
      v_stage := 'due_in_1';
    elsif v_days_remaining = 3 then
      v_stage := 'due_in_3';
    elsif v_days_remaining = 7 then
      v_stage := 'due_in_7';
    else
      continue;
    end if;

    v_subject := 'Invoice ' || v_row.invoice_number || ' -- ' ||
      case v_stage
        when 'due_in_7' then 'due in 7 days'
        when 'due_in_3' then 'due in 3 days'
        when 'due_in_1' then 'due tomorrow'
        when 'due_today' then 'due today'
        when 'grace_period_started' then 'payment overdue, grace period active'
      end;
    v_body := v_row.company_name || ': invoice ' || v_row.invoice_number || ' for ' ||
      v_row.currency || ' ' || v_row.total || ' is due ' || v_row.due_date || '.';

    begin
      insert into public.billing_reminders (company_id, invoice_id, stage, channel)
        values (v_row.company_id, v_row.invoice_id, v_stage, 'in_app');

      insert into public.notifications (company_id, audience, channel, recipient_user_id, category, subject, body, sent_at)
        values (v_row.company_id, 'company_admin', 'in_app', null,
                case v_stage when 'grace_period_started' then 'grace_period_started' else 'renewal_upcoming' end,
                v_subject, v_body, now());

      company_id := v_row.company_id;
      invoice_id := v_row.invoice_id;
      stage := v_stage;
      return next;
    exception when unique_violation then
      -- This exact (invoice, stage, channel) reminder was already sent by
      -- an earlier or overlapping run -- safe no-op, nothing double-sent.
      continue;
    end;
  end loop;
end;
$$;

comment on function send_due_billing_reminders() is
  'Phase 6C: for every pending subscription invoice, computes the company-local days-remaining-until-due (or detects an active grace period) and, at most once per (invoice, stage) via billing_reminders'' unique constraint, records the reminder and creates a company-wide (recipient_user_id null, visible to any member with billing.view via notifications'' existing RLS policy) in_app notifications row. No email is ever sent from this function -- see migration header point 8 for why.';

revoke all on function send_due_billing_reminders() from public, anon, authenticated;
grant execute on function send_due_billing_reminders() to service_role;

-- ---------------------------------------------------------------------------
-- 8. admin_billing_lifecycle_overview: Super-Admin-only read RPC answering
--    Phase 6C's "admin-ready billing data" requirement without building a
--    UI. Gating mirrors admin_assign_plan (migration 17) exactly.
-- ---------------------------------------------------------------------------

create or replace function admin_billing_lifecycle_overview()
returns table (
  company_id uuid,
  company_name text,
  subscription_state subscription_state,
  current_period_end timestamptz,
  grace_period_end timestamptz,
  latest_invoice_id uuid,
  latest_invoice_number text,
  latest_invoice_status invoice_status,
  latest_invoice_due_date date,
  latest_invoice_total numeric,
  latest_invoice_currency text,
  days_until_due integer,
  is_overdue boolean,
  last_paid_invoice_id uuid,
  last_paid_date date,
  last_paid_amount numeric
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null then raise exception 'unauthorized'; end if;
  if public.current_platform_role() is distinct from 'super_admin' then raise exception 'permission_denied'; end if;

  return query
  select
    c.id,
    c.name,
    s.state,
    s.current_period_end,
    s.grace_period_end,
    li.id,
    li.invoice_number,
    li.status,
    li.due_date,
    li.total,
    li.currency,
    (li.due_date - (now() at time zone coalesce(c.timezone, 'UTC'))::date)::integer,
    (li.status = 'pending' and li.due_date < (now() at time zone coalesce(c.timezone, 'UTC'))::date),
    lp.id,
    lp.paid_date,
    lp.total
  from public.companies c
  join public.subscriptions s on s.company_id = c.id
  left join lateral (
    select i.* from public.invoices i
    where i.company_id = c.id and i.kind = 'subscription'
    order by i.created_at desc limit 1
  ) li on true
  left join lateral (
    select i.* from public.invoices i
    where i.company_id = c.id and i.kind = 'subscription' and i.status = 'paid'
    order by i.paid_date desc nulls last limit 1
  ) lp on true;
end;
$$;

comment on function admin_billing_lifecycle_overview() is
  'Phase 6C: Super-Admin-only (current_platform_role() = ''super_admin'', not merely is_platform_staff()) read-only overview answering "companies due in N days / overdue / grace period / suspended for non-payment / paid this month / payment date+amount" without a dedicated reporting table -- callers filter/aggregate the returned rows client-side. No Super Admin UI is built to consume this in Phase 6C; the RPC exists so that UI can be added later without further schema work.';

revoke all on function admin_billing_lifecycle_overview() from public, anon;
grant execute on function admin_billing_lifecycle_overview() to authenticated;
